name: Build
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
    paths:
      - .github/workflows/build.yaml
      - 'images/**'
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/ubuntu
        context: images/ubuntu/latest
        buildargs: UBUNTU_RELEASE_NAME=focal
        tags: "focal,20.04,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_ubuntu:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_ubuntu
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/ubuntu
        readme-filepath: ./images/ubuntu/README.md
        short-description: "StratoSpire ubuntu image"
  build_buildpack_deps_curl:
    runs-on: ubuntu-latest
    needs:
      - build_ubuntu
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/buildpack-deps
        context: images/buildpack-deps/curl/latest
        buildargs: UBUNTU_RELEASE_NAME=focal
        tags: "curl-focal,curl-ubuntu,curl"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  build_buildpack_deps_scm:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps_curl
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/buildpack-deps
        context: images/buildpack-deps/scm/latest
        buildargs: UBUNTU_RELEASE_NAME=focal
        tags: "scm-focal,scm-ubuntu,scm"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  build_buildpack_deps:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps_scm
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/buildpack-deps
        context: images/buildpack-deps/latest
        buildargs: UBUNTU_RELEASE_NAME=focal
        tags: "focal,ubuntu,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_buildpack_deps:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/buildpack-deps
        readme-filepath: ./images/buildpack-deps/README.md
        short-description: "StratoSpire buildpack-deps images"
  build_node:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/node
        context: images/node/latest
        buildargs: UBUNTU_RELEASE_NAME=focal,NODE_VERSION=14.17.1
        tags: "14.17.1-focal,14.17.1-ubuntu,14.17.1,14.17-focal,14.17-ubuntu,14.17,focal,ubuntu,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_node:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_node
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/node
        readme-filepath: ./images/node/README.md
        short-description: "StratoSpire node image"
  build_erlang:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/erlang
        context: images/erlang/latest
        buildargs: UBUNTU_RELEASE_NAME=focal,OTP_VERSION=24.0.2,REBAR3_VERSION=3.16.1,REBAR_VERSION=2.6.4
        tags: "24.0.2-focal,24.0.2-ubuntu,24.0.2,24.0-focal,24.0-ubuntu,24.0,focal,ubuntu,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_erlang:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_erlang
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/erlang
        readme-filepath: ./images/erlang/README.md
        short-description: "StratoSpire erlang image"
  build_elixir:
    runs-on: ubuntu-latest
    needs:
      - build_erlang
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/elixir
        context: images/elixir/latest
        buildargs: UBUNTU_RELEASE_NAME=focal,OTP_VERSION=24.0.2,ELIXIR_VERSION=v1.12.1
        tags: "1.12.1-focal,1.12.1-ubuntu,1.12.1,1.12-focal,1.12-ubuntu,1.12,focal,ubuntu,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_elixir:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_elixir
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/elixir
        readme-filepath: ./images/elixir/README.md
        short-description: "StratoSpire elixir image"
  build_golang:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps_scm
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/golang
        context: images/golang/latest
        buildargs: UBUNTU_RELEASE_NAME=focal,GOLANG_VERSION=1.16.5
        tags: "1.16.5-focal,1.16.5-ubuntu,1.16.5,1.16-focal,1.16-ubuntu,1.16,focal,ubuntu,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_golang:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_golang
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/golang
        readme-filepath: ./images/golang/README.md
        short-description: "StratoSpire golang image"
  build_python:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/python
        context: images/python/latest
        buildargs: UBUNTU_RELEASE_NAME=focal,PYTHON_VERSION=3.9.5,PYTHON_PIP_VERSION=21.1.2
        tags: "3.9.5-focal,3.9.5-ubuntu,3.9.5,3.9-focal,3.9-ubuntu,3.9,focal,ubuntu,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_python:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_python
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/python
        readme-filepath: ./images/python/README.md
        short-description: "StratoSpire python image"
  build_wal_g:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps_scm
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/wal-g
        context: images/wal-g/latest
        buildargs: UBUNTU_RELEASE_NAME=focal,UBUNTU_RELEASE_NUM=20.04,WAL_G_VERSION=1.0,WAL_G_DATABASE=pg
        tags: "pg-1.0-focal,pg-1.0,1.0,pg,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_wal_g:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_wal_g
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/wal-g
        readme-filepath: ./images/wal-g/README.md
        short-description: "StratoSpire wal-g image"
  build_kubectl:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps_scm
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/kubectl
        context: images/kubectl/latest
        buildargs: UBUNTU_RELEASE_NAME=focal,K8S_VERSION=1.21.1
        tags: "1.21.1-focal,1.21-focal,1.21.1,1.21,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_kubectl:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_kubectl
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/kubectl
        readme-filepath: ./images/kubectl/README.md
        short-description: "StratoSpire kubectl image"
  build_helm:
    runs-on: ubuntu-latest
    needs:
      - build_kubectl
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/helm
        context: images/helm/latest
        buildargs: UBUNTU_RELEASE_NAME=focal,HELM_VERSION=3.6.1
        tags: "3.6.1-focal,3.6-focal,3.6.1,3.6,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_helm:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_helm
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/helm
        readme-filepath: ./images/helm/README.md
        short-description: "StratoSpire helm image"
  build_terraform:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps_scm
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/terraform
        context: images/terraform/latest
        buildargs: UBUNTU_RELEASE_NAME=focal,TERRAFORM_VERSION=1.0.0
        tags: "1.0.0-focal,1.0-focal,1.0.0,1.0,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_terraform:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_terraform
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/terraform
        readme-filepath: ./images/terraform/README.md
        short-description: "StratoSpire terraform image"
  build_ci:
    runs-on: ubuntu-latest
    needs:
      - build_node
      - build_golang
      - build_elixir
      - build_ubuntu
      - build_python
      - build_kubectl
      - build_helm
      - build_terraform
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        DOCKER_BUILDKIT: "1"
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/ci
        context: images/ci/latest
        tags: "focal,ubuntu,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
        snapshot: true
  update_hub_ci:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_ci
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/ci
        readme-filepath: ./images/ci/README.md
        short-description: "StratoSpire ci image"
