name: Build
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
    paths:
      - .github/workflows/build.yaml
      - 'images/**'
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/ubuntu
        context: images/ubuntu/latest
        buildargs: UBUNTU_RELEASE_NAME=focal
        tags: "focal,20.04,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_ubuntu:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_ubuntu
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/ubuntu
        readme-filepath: ./images/ubuntu/README.md
        short-description: "StratoSpire ubuntu image"
  build_buildpack_deps_curl:
    runs-on: ubuntu-latest
    needs:
      - build_ubuntu
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/buildpack-deps
        context: images/buildpack-deps/curl/latest
        buildargs: UBUNTU_RELEASE_NAME=focal
        tags: "curl-focal,curl-ubuntu,curl"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  build_buildpack_deps_scm:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps_curl
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/buildpack-deps
        context: images/buildpack-deps/scm/latest
        buildargs: UBUNTU_RELEASE_NAME=focal
        tags: "scm-focal,scm-ubuntu,scm"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  build_buildpack_deps:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps_scm
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/buildpack-deps
        context: images/buildpack-deps/latest
        buildargs: UBUNTU_RELEASE_NAME=focal
        tags: "focal,ubuntu,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_buildpack_deps:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/buildpack-deps
        readme-filepath: ./images/buildpack-deps/README.md
        short-description: "StratoSpire buildpack-deps images"
  build_python:
    runs-on: ubuntu-latest
    needs:
      - build_buildpack_deps
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/python
        context: images/python/latest
        buildargs: UBUNTU_RELEASE_NAME=focal,PYTHON_VERSION=3.9.5,PYTHON_PIP_VERSION=21.1.2
        tags: "3.9.5-focal,3.9.5-ubuntu,3.9.5,focal,ubuntu,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_python:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_python
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/python
        readme-filepath: ./images/python/README.md
        short-description: "StratoSpire python image"
  build_wal_g:
    runs-on: ubuntu-latest
    needs:
      - build_ubuntu
    steps:
    - uses: actions/checkout@master
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: stratospire/wal-g
        context: images/wal-g/latest
        buildargs: UBUNTU_RELEASE_NAME=focal,UBUNTU_RELEASE_NUM=20.04,WAL_G_VERSION=1.0,WAL_G_DATABASE=pg
        tags: "pg-1.0-focal,pg-1.0,1.0,pg,latest"
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/main' }}
  update_hub_wal_g:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build_wal_g
    steps:
    - uses: actions/checkout@master
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stratospire/wal-g
        readme-filepath: ./images/wal-g/README.md
        short-description: "StratoSpire wal-g image"
